# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eezhee < Formula
  desc "The easiest and fastest way to create a kubernutes cluster on a variety of clouds"
  homepage "https://github.com/eezhee/eezhee"
  version "0.2.10"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/eezhee/eezhee/releases/download/v0.2.10/eezhee_0.2.10_Darwin_x86_64.tar.gz"
    sha256 "5c29446d1dd3263664a29506bd4faff5af5aee3255890a10aeae04eb57b75692"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/eezhee/eezhee/releases/download/v0.2.10/eezhee_0.2.10_Darwin_arm64.tar.gz"
    sha256 "f3849725a4f034455127240a221c71b94db5813d1bc21fc438bcc26c4e5a9365"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/eezhee/eezhee/releases/download/v0.2.10/eezhee_0.2.10_Linux_x86_64.tar.gz"
    sha256 "bfdd494aab7153f7634e172a66660e43060e1fe5959b64472537409c150cd349"
  end

  def install
    bin.install "eezhee"
  end
end
