# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eezhee < Formula
  desc "The easiest and fastest way to create a kubernutes cluster on a variety of clouds"
  homepage "https://github.com/eezhee/eezhee"
  version "0.2.8"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/eezhee/eezhee/releases/download/v0.2.8/eezhee_0.2.8_Darwin_x86_64.tar.gz"
    sha256 "529abb8730a6d3dfbfa9c3d597aa39490165781f4312234810ed37eb534de57a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/eezhee/eezhee/releases/download/v0.2.8/eezhee_0.2.8_Darwin_arm64.tar.gz"
    sha256 "06c4d29b4b9225d99d7842ced9dde5466e72cb35f33542f52bcb9f921b677498"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/eezhee/eezhee/releases/download/v0.2.8/eezhee_0.2.8_Linux_x86_64.tar.gz"
    sha256 "7fb7f4f4984b2dd7d9e91acd0c91035e49ea37bf7509909c00c7c7eabedf1f23"
  end

  def install
    bin.install "eezhee"
  end
end
